### ISSUE TITLE
password

### ISSUE THREAD

**Issue by roger-ux** [2214452605/StudentDormitoryManagementSystem#5]
登陆密码是啥呀？

**Comment by zhangzengyue** [comment]
123456，看后台sql文件

**Comment by renzihao206** [comment]
sdms.sql怎么导入到mongodb中可以说一下吗

**Comment by Hxxing123** [comment]
为什么我用sql文件里的哪一个账号输入都是提示账号不存在？哪里出问题了

**Comment by Finedl** [comment]
sdms.sql怎么导入到mongodb中可以说一下吗
同问，就很奇怪，mongo怎么是sql文件

**Comment by renzihao206** [comment]
快忘记了&nbsp; 记得通过navcait




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xianjuyao/StudentDormitoryManagementSystem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 下午3:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xianjuyao/StudentDormitoryManagementSystem] password (#5)





 
sdms.sql怎么导入到mongodb中可以说一下吗
 同问，就很奇怪，mongo怎么是sql文件
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Finedl** [comment]
卧槽，XD有没有空远程帮我配置下，前端Vue和node.js都启动成功了，就是这个sdms.sql+mongoDB数据库折腾好久了。



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "xianjuyao/StudentDormitoryManagementSystem"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Nov 9, 2021 03:27 PM
***@***.***&gt;;
Cc:&nbsp;"Dongliang ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [xianjuyao/StudentDormitoryManagementSystem] password (#5)





 快忘记了&amp;nbsp; 记得通过navcait 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xianjuyao/StudentDormitoryManagementSystem"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月9日(星期二) 下午3:23 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [xianjuyao/StudentDormitoryManagementSystem] password (#5) 
 
 
 
 
 
   
 sdms.sql怎么导入到mongodb中可以说一下吗 
  同问，就很奇怪，mongo怎么是sql文件 
   
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Finedl** [comment]
需要参考这个连接吗：将.xlsx和.sql文件导入mongodb?   
https://blog.csdn.net/iamxuhuimin/article/details/53465985?utm_source=blogxgwz8

**Comment by renzihao206** [comment]
你这是哪个项目啊&nbsp; &nbsp;博客吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xianjuyao/StudentDormitoryManagementSystem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xianjuyao/StudentDormitoryManagementSystem] password (#5)





 
需要参考这个连接吗：将.xlsx和.sql文件导入mongodb?
 https://blog.csdn.net/iamxuhuimin/article/details/53465985?utm_source=blogxgwz8
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Finedl** [comment]
https://github.com/xianjuyao/StudentDormitoryManagementSystem
vue.js+Node.js+mongodb制作的一个实现了基本功能的学生宿舍管理系统



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "xianjuyao/StudentDormitoryManagementSystem"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Nov 9, 2021 03:40 PM
***@***.***&gt;;
Cc:&nbsp;"Dongliang ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [xianjuyao/StudentDormitoryManagementSystem] password (#5)





 你这是哪个项目啊&amp;nbsp; &amp;nbsp;博客吗 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xianjuyao/StudentDormitoryManagementSystem"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月9日(星期二) 下午3:38 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [xianjuyao/StudentDormitoryManagementSystem] password (#5) 
 
 
 
 
 
   
 需要参考这个连接吗：将.xlsx和.sql文件导入mongodb? 
  https://blog.csdn.net/iamxuhuimin/article/details/53465985?utm_source=blogxgwz8 
   
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Finedl** [comment]
已经ok了



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 9, 2021 15:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xianjuyao/StudentDormitoryManagementSystem] password (#5)




 你这是哪个项目啊&amp;nbsp; &amp;nbsp;博客吗 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xianjuyao/StudentDormitoryManagementSystem"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月9日(星期二) 下午3:38 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [xianjuyao/StudentDormitoryManagementSystem] password (#5) 
 
 
 
 
 
   
 需要参考这个连接吗：将.xlsx和.sql文件导入mongodb? 
  https://blog.csdn.net/iamxuhuimin/article/details/53465985?utm_source=blogxgwz8 
   
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
